[[Xorg_xkeyboard_config]]
arch = "armv7l"
git-tree-sha1 = "95e5ff72ba60be879dc03513c29b7e8b53102c66"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "ebf0af001fe5832919bff73fbb68b3cfc6b6c08cc6c6f0ef3cd18eeec0ea044c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.arm-linux-gnueabihf.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "x86_64"
git-tree-sha1 = "13c9bf84cfbc60f994c77b524434d9c57d6a1d4b"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "45e587fee2433d2cf5953d47aaa49b072762fcff3af20b675a30d2c65aaeba28"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "aarch64"
git-tree-sha1 = "e71bd2767121732ef839b63e40c45842706f8b6b"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "08c77e04660aabf3e60ab24e9f7f88aab08fe7d7a029e4f76b9b4d5ac3a415c3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "i686"
git-tree-sha1 = "336d6202bfd671b54c8466777e8dc5ee64ce94d5"
libc = "musl"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "9ffcf47c7f843e93f94c24cfe77e82a50d9575acc45393e09718e5be9b54e158"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.i686-linux-musl.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "aarch64"
git-tree-sha1 = "4848814b7749c55033af6d571478bc802772e27e"
libc = "musl"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "44b55c134507c9395500adb23c028a89e8e0ca236218eaf6811c7b6f25156373"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.aarch64-linux-musl.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "x86_64"
git-tree-sha1 = "5c76da89967e740966ea6e22494f2fab375da3d5"
os = "freebsd"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "7cf6203568de015b536ddb8aa26e7658898b030d56902e69df312e873f66c5a8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "powerpc64le"
git-tree-sha1 = "584eda531542241fbb944cfe84798dafa9fb56db"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "59dd0683ca23b93322914ac60555176cc9f27c37ccbdb3ca18f37dcdb2242dce"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "i686"
git-tree-sha1 = "9c56444b95b43a30e05bc0b7714d754a6dac6050"
libc = "glibc"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "0713dc2e351c5aa9f8bed972a92172e06a6223fedb64ac69a8703424cd8b61b7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.i686-linux-gnu.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "x86_64"
git-tree-sha1 = "88e54bd17d71479187ccb91838d1bc84702e349d"
libc = "musl"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "fcc5eafe7cec8f4939214058bfde70190309e129c0d4138de09a139d71e1a7c9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.x86_64-linux-musl.tar.gz"
[[Xorg_xkeyboard_config]]
arch = "armv7l"
git-tree-sha1 = "816433d59e6865c8f451d6f9880878ba18646c65"
libc = "musl"
os = "linux"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "2e81506f6b22e2d12588c4850b13d84561242775169aca252ddcffb6913c957e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+1/Xorg_xkeyboard_config.v2.27.0.arm-linux-musleabihf.tar.gz"
