[Xorg_xkeyboard_config]
git-tree-sha1 = "051bcd87a956c48ab829b7da04a56222c10f0a47"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "857e8f1e86203b5d576f59d7e461a3f513b612c13654c51a0e09e6e9f45a963e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.47.0+0/Xorg_xkeyboard_config.v2.47.0.any.tar.gz"
