[Xorg_xkeyboard_config]
git-tree-sha1 = "23d821271a00e164eb2b5c273985da44f9a831a1"

    [[Xorg_xkeyboard_config.download]]
    sha256 = "529c47322a2c21a3d35104f29dc2cc220f3dbf0c94eae03e3dccd0c0671360cc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.44.0+0/Xorg_xkeyboard_config.v2.44.0.any.tar.gz"
